=== Opening-ETDs/etd-dtd/etd.xml.dtd
<!--
  PROJECT: <ETD> Electronic Thesis and Dissertation Project
   AUTHOR: Neill Kipp, nkipp@vt.edu
  VERSION: 1.1
  RUNDATE: Mon Feb 24 23:18:27 EST 1997

  This file was generated with the "etdtangle.pl" Perl script,
  as if the source file were a literate program.  All information between 
  <pre> and </pre> comes here.

  DO NOT EDIT THIS FILE DIRECTLY!
    Rerun the following:
      sgmls sgml.dec myfile.etd | etdtangle.pl > myfile.source

-->
<!-- 
Document Type Definition
Electronic Theses and Dissertations
Virginia Polytechnic Institute and State University

Neill A. Kipp, Document Editor
nkipp@vt.edu

Version 0.9.6
January 28, 1997

http://etd.vt.edu/etd/
etd@vt.edu
-->

<!-- 
<!ENTITY % etd PUBLIC 
  "-//VT//DTD Electronic Theses and Dissertations 0.9.6//EN">
-->

<!ELEMENT etd    ( front, body, back, ( footnote | float ) ) >

<!-- Front matter -->

<!ELEMENT front 
  ( title, author, submission, school, degree, major, approvals, date, city, state, 
  keywords, copyright, abstract, 
  grant?, dedication?, acknowledgments? ) >

<!ELEMENT title 
  ( #PCDATA | em | strong | tt | q | term | foreign | 
   im | link | target | a | sup | sub | br | 
   worktitle | articletitle )* >

<!ELEMENT author  ( ( given, surname, suffix? ) | organization )  >

<!ELEMENT given 
  ( #PCDATA | em | strong | tt | q | term | foreign | 
   im | link | target | a | sup | sub | br )* >

<!ELEMENT surname 
  ( #PCDATA | em | strong | tt | q | term | foreign | 
   im | link | target | a | sup | sub | br )* >

<!ELEMENT suffix 
  ( #PCDATA | em | strong | tt | q | term | foreign | 
   im | link | target | a | sup | sub | br )*  >

<!ELEMENT organization 
  ( #PCDATA | em | strong | tt | q | term | foreign | 
   im | link | target | a | sup | sub | br )* >


<!ELEMENT submission 
  ( #PCDATA | em | strong | tt | q | term | foreign | 
   im | link | target | a | sup | sub | br )* >

<!ELEMENT school 
  ( #PCDATA | em | strong | tt | q | term | foreign | 
   im | link | target | a | sup | sub | br )* >

<!ELEMENT degree 
  ( #PCDATA | em | strong | tt | q | term | foreign | 
   im | link | target | a | sup | sub | br )* >

<!ELEMENT major  
  ( #PCDATA | em | strong | tt | q | term | foreign | 
   im | link | target | a | sup | sub | br )* >

<!ELEMENT approvals  ( name* ) >

<!ELEMENT name 
  ( #PCDATA | em | strong | tt | q | term | foreign | 
   im | link | target | a | sup | sub | br )* >

<!ELEMENT date 
  ( #PCDATA | em | strong | tt | q | term | foreign | 
   im | link | target | a | sup | sub | br )* >

<!ELEMENT city 
  ( #PCDATA | em | strong | tt | q | term | foreign | 
   im | link | target | a | sup | sub | br )* >

<!ELEMENT state 
  ( #PCDATA | em | strong | tt | q | term | foreign | 
   im | link | target | a | sup | sub | br )* >

<!ELEMENT keywords  ( keyword+ ) >

<!ELEMENT keyword  
  ( #PCDATA | em | strong | tt | q | term | foreign | 
   im | link | target | a | sup | sub | br | 
   worktitle | articletitle )* >

<!ELEMENT copyright 
  ( #PCDATA | em | strong | tt | q | term | foreign | 
   im | link | target | a | sup | sub | br | 
   worktitle | articletitle )* >

<!ELEMENT abstract 
  ( #PCDATA | em | strong | tt | q | term | foreign | 
   im | link | target | a | sup | sub | br | 
   worktitle | articletitle | p | citation | table | mm )* >

<!ATTLIST abstract
  id ID #IMPLIED
>

<!ELEMENT grant 
  ( #PCDATA | em | strong | tt | q | term | foreign | 
   im | link | target | a | sup | sub | br | 
   worktitle | articletitle | p | citation | table | mm )* >

<!ATTLIST grant 
  id ID #IMPLIED 
>

<!ELEMENT dedication  ( head?, ( p | citation | table | mm)* ) >

<!ATTLIST dedication
  id ID #IMPLIED
>

<!ELEMENT acknowledgments  ( head?, ( p | citation | table | mm)* ) >

<!ATTLIST acknowledgments
  id ID #IMPLIED
>

<!-- Body matter -->

<!ELEMENT body  ( chapter+ ) >

<!-- 1. -->
<!ENTITY % chapterInclusions "" >
<!ELEMENT chapter  
  ( head?,  ( p | citation | table | mm)*, section* ) %chapterInclusions; >

<!ATTLIST chapter
  id ID #IMPLIED
>

<!-- 1.2 -->
<!ELEMENT section  
  ( head?, ( p | citation | table | mm)*, subsection* ) >

<!ATTLIST section
  id ID #IMPLIED
>

<!-- 1.2.3 -->
<!ELEMENT subsection  
  ( head?, ( p | citation | table | mm)*, block* ) >

<!ATTLIST subsection
  id ID #IMPLIED
>

<!-- 1.2.3.4 -->
<!ELEMENT block  
  ( head?, ( p | citation | table | mm)*, subblock* ) >

<!ATTLIST block
  id ID #IMPLIED
>

<!-- 1.2.3.4.5 -->
<!ELEMENT subblock  
  ( head?, ( p | citation | table | mm)* ) >

<!ATTLIST subblock
  id ID #IMPLIED
>

<!ENTITY % paragraphInclusions "" >
<!ELEMENT p  ( #PCDATA | head | em | strong | tt | q | term | foreign | 
   im | link | target | a | sup | sub | br | 
   worktitle | articletitle | 
   ol | ul | dl | pre | verse | blockquote | attrib | math )* %paragraphInclusions; >

<!ELEMENT head 
  ( #PCDATA | em | strong | tt | q | term | foreign | 
   im | link | target | a | sup | sub | br | 
   worktitle | articletitle )* >

<!ELEMENT em 
  ( #PCDATA | em | strong | tt | q | term | foreign | 
   im | link | target | a | sup | sub | br | 
   worktitle | articletitle )* >

<!ELEMENT strong 
  ( #PCDATA | em | strong | tt | q | term | foreign | 
   im | link | target | a | sup | sub | br | 
   worktitle | articletitle )* >

<!ELEMENT br  EMPTY >

<!ELEMENT tt  ( #PCDATA )* >

<!ELEMENT q 
  ( #PCDATA | em | strong | tt | q | term | foreign | 
   im | link | target | a | sup | sub | br | 
   worktitle | articletitle )* >

<!ELEMENT term 
  ( #PCDATA | em | strong | tt | q | term | foreign | 
   im | link | target | a | sup | sub | br | 
   worktitle | articletitle )* >

<!ELEMENT foreign 
  ( #PCDATA | em | strong | tt | q | term | foreign | 
   im | link | target | a | sup | sub | br | 
   worktitle | articletitle )* >

<!ELEMENT im  ( #PCDATA )* >

<!ATTLIST im
  id ID #IMPLIED
  notation NOTATION (TeX) "TeX"
>

<!ELEMENT sup 
  ( #PCDATA | em | strong | tt | q | term | foreign | 
   im | link | target | a | sup | sub | br | 
   worktitle | articletitle )* >

<!ELEMENT sub 
  ( #PCDATA | em | strong | tt | q | term | foreign | 
   im | link | target | a | sup | sub | br | 
   worktitle | articletitle )* >

<!ENTITY amp  "&amp;" >

<!ENTITY lt  "<" >

<!ENTITY gt  ">" >

<!ENTITY quot  '"' >

<!ELEMENT pre  ( #PCDATA )*  >

<!ATTLIST pre
  id ID #IMPLIED
  outfile CDATA #IMPLIED
>

<!ELEMENT blockquote 
  ( #PCDATA | em | strong | tt | q | term | foreign | 
   im | link | target | a | sup | sub | br | 
   worktitle | articletitle | p | citation | table | mm )* >

<!-- 
For example,

<blockquote>Rosencrantz and Guildenstern are dead</>
<attrib>William Shakespeare, <worktitle>Hamlet, Prince of Denmark</>, 
Act V, Scene II.</>
-->

<!ELEMENT attrib  
  ( #PCDATA | em | strong | tt | q | term | foreign | 
   im | link | target | a | sup | sub | br | 
   worktitle | articletitle )* >

<!ELEMENT verse  ( head?, stanza+ ) >

<!ATTLIST verse 
  id ID #IMPLIED
>

<!--
For example,
<verse>
<stanza>
<speaker>Petruchio
  <line>But here she comes; now, Petruchio, speak.
  <stage>Enter Katherina
  <line>Good morrow, Kate- for that's your name, I hear
<speaker>Katherina
  <line>Well have you heard, but something hard of hearing:
  <line>They call me Katherine that do talk of me. 

<attrib>William Shakespeare, <worktitle>Taming of the Shrew</>, Act II, Scene I
-->

<!ELEMENT stanza  ( speaker | line | stage )+ >

<!ELEMENT speaker 
  ( #PCDATA | em | strong | tt | q | term | foreign | 
   im | link | target | a | sup | sub | br | 
   worktitle | articletitle )* >

<!ELEMENT line 
  ( #PCDATA | em | strong | tt | q | term | foreign | 
   im | link | target | a | sup | sub | br | 
   worktitle | articletitle )* >

<!-- for line numbering -->
<!ATTLIST line 
  id ID #IMPLIED
  indented (indent|noindent) "noindent" 
  number CDATA #IMPLIED
>

<!ELEMENT stage 
  ( #PCDATA | em | strong | tt | q | term | foreign | 
   im | link | target | a | sup | sub | br | 
   worktitle | articletitle )* >

<!ATTLIST stage 
  id ID #IMPLIED
>

<!ELEMENT math  ( #PCDATA )* >

<!ATTLIST math
  id ID #IMPLIED
  notation NOTATION (TeX) "TeX"
>

<!NOTATION TeX SYSTEM "">

<!ELEMENT ol  ( li )+ >

<!-- numbering: indicates the enumerator for this level of list
     (default: use in the order listed and circle back
     to arabic six-level nestings and beyond) -->
<!ATTLIST ol
  id ID #IMPLIED
  numbering ( arabic | lalpha | lroman | uroman | ualpha ) #IMPLIED 
>

<!ELEMENT ul  ( li )+ >

<!ATTLIST ul
  id ID #IMPLIED
>

<!ELEMENT li  ( #PCDATA | head | ol | ul | dl | 
  em | strong | tt | q | term | foreign | 
   im | link | target | a | sup | sub | br | 
   worktitle | articletitle | p | citation | table | mm )* >

<!ELEMENT dl  ( dt, dd )+ >

<!ELEMENT dt 
  ( #PCDATA | em | strong | tt | q | term | foreign | 
   im | link | target | a | sup | sub | br | 
   worktitle | articletitle )* >

<!ELEMENT dd  ( #PCDATA | head | ol | ul | dl | 
  em | strong | tt | q | term | foreign | 
   im | link | target | a | sup | sub | br | 
   worktitle | articletitle | p | citation | table | mm )* >

<!-- 
Example usage:
    <a href="http://etd.vt.edu/etd/">ETD Home Page</a>
    <a href="mailto:etd@vt.edu">etd@vt.edu</a>
-->

<!ELEMENT a 
  ( #PCDATA | em | strong | tt | q | term | foreign | 
   im | link | target | a | sup | sub | br | 
   worktitle | articletitle )* >

<!ATTLIST a 
  href CDATA #REQUIRED
>

<!-- goesto refers to: 
  target, footnote, citation, float, chapter, section, etc. -->
  
<!ELEMENT link 
  ( #PCDATA | em | strong | tt | q | term | foreign | 
   im | link | target | a | sup | sub | br | 
   worktitle | articletitle )* >

<!-- goesto: refers to another identifier in this document -->
<!ATTLIST link
  id ID #IMPLIED
  HyTime NMTOKEN "clink"
  goesto IDREF #REQUIRED
>

<!ELEMENT target 
  ( #PCDATA | em | strong | tt | q | term | foreign | 
   im | link | target | a | sup | sub | br | 
   worktitle | articletitle )* >

<!ATTLIST target 
  id ID #IMPLIED
>

<!ELEMENT footnote 
  ( #PCDATA | em | strong | tt | q | term | foreign | 
   im | link | target | a | sup | sub | br | 
   worktitle | articletitle | p | citation | table | mm )* >

<!ATTLIST footnote
  id ID #REQUIRED
>

<!ELEMENT float  ( ( p | citation | table | mm )*, caption? ) >

<!ATTLIST float 
  id ID #REQUIRED
>

<!ELEMENT caption  
  ( #PCDATA | em | strong | tt | q | term | foreign | 
   im | link | target | a | sup | sub | br | 
   worktitle | articletitle )* >

<!ATTLIST caption
  id ID #IMPLIED
>

<!ELEMENT table  
  ( ( colhead, column+)* | ( rowhead, row+)* )
>

<!ATTLIST table 
  id ID #IMPLIED
>

<!ELEMENT colhead
  ( #PCDATA | em | strong | tt | q | term | foreign | 
   im | link | target | a | sup | sub | br | 
   worktitle | articletitle )* >
<!ELEMENT rowhead 
  ( #PCDATA | em | strong | tt | q | term | foreign | 
   im | link | target | a | sup | sub | br | 
   worktitle | articletitle )* >

<!ELEMENT column  ( c* | rowhead* ) >
<!ELEMENT row  ( c* | colhead* ) >

<!ELEMENT c 
  ( #PCDATA | em | strong | tt | q | term | foreign | 
   im | link | target | a | sup | sub | br | 
   worktitle | articletitle )* >

<!-- Multimedia object.  The optional content has information about
media format and file size. -->

<!ELEMENT mm 
  ( #PCDATA | em | strong | tt | q | term | foreign | 
   im | link | target | a | sup | sub | br | 
   worktitle | articletitle )* >

<!ATTLIST mm
  entity ENTITY #REQUIRED
>

<!-- Back matter -->

<!ELEMENT back  ( bibliography, appendix*, vita ) >

<!ELEMENT bibliography  ( head?, ( p | citation | table | mm)* ) >

<!ENTITY % citationInclusions "" >
<!ELEMENT citation  
  ( address | articletitle | bible | court | edition | editor | email |
  handle | note | number | pages | pubdate | publisher | url | version |
  volume | workauthor | worktitle )*
  %citationInclusions;>

<!-- worktype: tells what sort of work is being cited, 
     i.e., book, journal, proceedings, video, WWW page, etc. -->
<!-- published: tells if the work was actually published -->
<!ATTLIST citation
  id ID #IMPLIED
  worktype CDATA #REQUIRED
  published ( published | unpublished ) "published"
>

<!ELEMENT address  
   ( #PCDATA | em | strong | tt | q | term | foreign | 
   im | link | target | a | sup | sub | br )* >
<!ELEMENT articletitle 
   ( #PCDATA | em | strong | tt | q | term | foreign | 
   im | link | target | a | sup | sub | br )* >
<!ELEMENT bible 
   ( #PCDATA | em | strong | tt | q | term | foreign | 
   im | link | target | a | sup | sub | br )* >
<!ELEMENT court
   ( #PCDATA | em | strong | tt | q | term | foreign | 
   im | link | target | a | sup | sub | br )* >
<!ELEMENT edition
   ( #PCDATA | em | strong | tt | q | term | foreign | 
   im | link | target | a | sup | sub | br )* >
<!ELEMENT editor
   ( #PCDATA | em | strong | tt | q | term | foreign | 
   im | link | target | a | sup | sub | br )* >
<!ELEMENT email
   ( #PCDATA | em | strong | tt | q | term | foreign | 
   im | link | target | a | sup | sub | br )* >
<!ELEMENT handle
   ( #PCDATA | em | strong | tt | q | term | foreign | 
   im | link | target | a | sup | sub | br )* >
<!ELEMENT note
   ( #PCDATA | em | strong | tt | q | term | foreign | 
   im | link | target | a | sup | sub | br )* >
<!ELEMENT number
   ( #PCDATA | em | strong | tt | q | term | foreign | 
   im | link | target | a | sup | sub | br )* >
<!ELEMENT pages
   ( #PCDATA | em | strong | tt | q | term | foreign | 
   im | link | target | a | sup | sub | br )* >
<!ELEMENT pubdate
   ( #PCDATA | em | strong | tt | q | term | foreign | 
   im | link | target | a | sup | sub | br )* >
<!ELEMENT publisher
   ( #PCDATA | em | strong | tt | q | term | foreign | 
   im | link | target | a | sup | sub | br )* >
<!ELEMENT url
   ( #PCDATA | em | strong | tt | q | term | foreign | 
   im | link | target | a | sup | sub | br )* >
<!ELEMENT version
   ( #PCDATA | em | strong | tt | q | term | foreign | 
   im | link | target | a | sup | sub | br )* >
<!ELEMENT volume
   ( #PCDATA | em | strong | tt | q | term | foreign | 
   im | link | target | a | sup | sub | br )* >
<!ELEMENT workauthor
   ( #PCDATA | em | strong | tt | q | term | foreign | 
   im | link | target | a | sup | sub | br )* >
<!ELEMENT worktitle 
   ( #PCDATA | em | strong | tt | q | term | foreign | 
   im | link | target | a | sup | sub | br )* >

<!ATTLIST address id ID #IMPLIED>
<!ATTLIST articletitle id ID #IMPLIED>
<!ATTLIST bible id ID #IMPLIED>
<!ATTLIST court id ID #IMPLIED>
<!ATTLIST edition id ID #IMPLIED>
<!ATTLIST editor id ID #IMPLIED>
<!ATTLIST email id ID #IMPLIED>
<!ATTLIST handle id ID #IMPLIED>
<!ATTLIST note id ID #IMPLIED>
<!ATTLIST number id ID #IMPLIED>
<!ATTLIST pages id ID #IMPLIED>
<!ATTLIST pubdate id ID #IMPLIED>
<!ATTLIST publisher id ID #IMPLIED>
<!ATTLIST url id ID #IMPLIED>
<!ATTLIST version id ID #IMPLIED>
<!ATTLIST volume id ID #IMPLIED>
<!ATTLIST workauthor id ID #IMPLIED>
<!ATTLIST worktitle id ID #IMPLIED>

<!ENTITY % appendixInclusions "" >
<!ELEMENT appendix  ( head?, ( p | citation | table | mm)*, section* ) %appendixInclusions; >

<!ATTLIST appendix 
  id ID #IMPLIED
>

<!ELEMENT vita  ( head?, ( p | citation | table | mm)* ) >

<!-- 
  This is an example document type declaration with subset.  
  It begins an SGML ETD.

<!DOCTYPE etd SYSTEM "etd.dtd" [
  <!NOTATION jpeg SYSTEM >
  <!ENTITY theatre SYSTEM "theatre.jpg" NDATA jpeg >
  <!ENTITY stratford SYSTEM "stratford.jpg" NDATA jpeg >
]>
<etd> 
<front>
<title>Use of Metaphor in Shakespeare's Plays ...
--> 

<!-- Inclusions -->

  <!ENTITY % chapterInclusions "" >

  <!ENTITY % chapterInclusions "+( mypara | myquote )" >

  <!ENTITY % appendixInclusions "" >

  <!ENTITY % citationInclusions "" >

  <!ENTITY % paragraphInclusions "" >

<!--
  End of Document, etdtangle.pl, Version 1.1
  RUNDATE: Mon Feb 24 23:18:27 EST 1997
-->

=== Opening-ETDs/etd-dtd/empty_etd_minimal.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE etd SYSTEM "file:/Users/waingram/Projects/etd-dtd/etd.xml.dtd">
<etd>
    <front>
        <title></title>
        <author>
            <given></given>
            <surname></surname>
            <suffix></suffix>
        </author>
        <submission></submission>
        <school></school>
        <degree></degree>
        <major></major>
        <approvals></approvals>
        <date></date>
        <city></city>
        <state></state>
        <keywords>
            <keyword></keyword>
        </keywords>
        <copyright></copyright>
        <abstract></abstract>
    </front>
    <body>
        <chapter></chapter>
    </body>
    <back>
        <bibliography></bibliography>
        <vita></vita>
    </back>
    <footnote id="x1"></footnote>
</etd>

=== Opening-ETDs/etd-dtd/empty_etd_optional.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE etd SYSTEM "file:/Users/waingram/Projects/etd_xml/etd.xml.dtd">
<etd>
    <front>
        <title></title>
        <author>
            <given></given>
            <surname></surname>
            <suffix></suffix>
        </author>
        <submission></submission>
        <school></school>
        <degree></degree>
        <major></major>
        <approvals>
            <name></name>
        </approvals>
        <date></date>
        <city></city>
        <state></state>
        <keywords>
            <keyword></keyword>
        </keywords>
        <copyright></copyright>
        <abstract></abstract>
        <grant></grant>
        <dedication>
            <head></head>
            <p></p>
        </dedication>
        <acknowledgments>
            <head></head>
            <p></p>
        </acknowledgments>
    </front>
    <body>
        <chapter>
            <head></head>
            <p></p>
            <section>
                <head></head>
                <p></p>
                <subsection>
                    <head></head>
                    <p></p>
                    <block>
                        <head></head>
                        <p></p>
                        <subblock>
                            <head></head>
                            <p></p>
                        </subblock>
                    </block>
                </subsection>
            </section>
        </chapter>
    </body>
    <back>
        <bibliography>
            <head></head>
            <p></p>
        </bibliography>
        <appendix>
            <head></head>
            <p></p>
            <section>
                <head></head>
                <p></p>
                <subsection>
                    <head></head>
                    <p></p>
                    <block>
                        <head></head>
                        <p></p>
                        <subblock>
                            <head></head>
                            <p></p>
                        </subblock>
                    </block>
                </subsection>
            </section>
        </appendix>
        <vita>
            <head></head>
            <p></p>
        </vita>
    </back>
    <footnote id="x1"></footnote>
</etd>
